services:
  - type: web
    name: bilbilak-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
